//! Schluesselwoerter (Referenz 2.2) und reservierte Woerter (2.5), Edition 1.
//!
//! Beide Listen sind sortiert, damit `binary_search` sie durchsucht. Der Test
//! `tests/keywords.rs` liest Abschnitt 2.2 aus `plan/definition.md` und vergleicht;
//! eine Abweichung bricht den Build.

/// Schluesselwoerter: leiten eine Aussage, Deklaration oder Klausel ein oder wirken
/// in Ausdruecken als Operator oder Literal (Regel in 2.2).
pub const KEYWORDS: &[&str] = &[
    "abort",
    "after",
    "alert",
    "always",
    "and",
    "arm",
    "as",
    "at",
    "block",
    "bound",
    "break",
    "campaign",
    "cancel",
    "case",
    "check",
    "command",
    "const",
    "default",
    "disarm",
    "driver",
    "elif",
    "else",
    "enter",
    "enum",
    "eventually",
    "every",
    "exit",
    "expect",
    "false",
    "fault",
    "fn",
    "for",
    "has",
    "if",
    "implies",
    "import",
    "in",
    "initial",
    "input",
    "instance",
    "job",
    "log",
    "loop",
    "machine",
    "match",
    "matches",
    "measure",
    "native",
    "never",
    "node",
    "none",
    "not",
    "on",
    "once",
    "or",
    "output",
    "param",
    "pass",
    "persist",
    "port",
    "profile",
    "program",
    "property",
    "pub",
    "pulse",
    "raise",
    "range",
    "record",
    "repeat",
    "return",
    "scenario",
    "send",
    "sequence",
    "signal",
    "stable",
    "state",
    "step",
    "stop_on",
    "stream",
    "sweep",
    "system",
    "then",
    "trigger",
    "true",
    "tunable",
    "type",
    "unit",
    "unitvec",
    "until",
    "var",
    "verdict",
    "verify",
    "wait",
    "when",
    "with",
];

/// Reservierte Woerter ohne Bedeutung; als Bezeichner verboten (2.5).
pub const RESERVED: &[&str] = &[
    "async", "await", "catch", "class", "defer", "export", "extern", "global", "impl", "module", "region", "select",
    "spawn", "static", "struct", "throw", "trait", "try", "union", "unsafe", "volatile", "where", "while", "yield",
];

/// Kontextuelle Terminale: alle uebrigen Woerter der Grammatik (2.3). Sie gelten nur an
/// ihrer Stelle und sind sonst Bezeichner; nach einer Zahl werden sie nie als Einheit
/// gelesen (lexer.md L4.3). Der Test vergleicht die Liste mit `grammar/takt.ebnf`.
pub const CONTEXTUAL: &[&str] = &[
    "Duration",
    "Edge",
    "affine",
    "align",
    "asap",
    "big",
    "bits",
    "bool",
    "boundary",
    "bytes",
    "call",
    "capacity",
    "capacity_bytes",
    "capture",
    "channels",
    "cobs",
    "cost",
    "debounce",
    "display",
    "doc",
    "drop",
    "drop_oldest",
    "duration",
    "eq",
    "expect_len",
    "f32",
    "f64",
    "fail",
    "fault_is_fail",
    "fixed",
    "float",
    "follows",
    "framing",
    "from",
    "group",
    "hex",
    "hw",
    "i16",
    "i32",
    "i64",
    "i8",
    "idle",
    "inout",
    "int",
    "integer",
    "irreversible",
    "jitter",
    "label",
    "language",
    "layout",
    "len",
    "length_prefixed",
    "line",
    "lines",
    "little",
    "map",
    "mat",
    "max_age",
    "max_rate",
    "max_slew",
    "mem",
    "min_interval",
    "mmio",
    "monitor",
    "numeric",
    "offset",
    "open",
    "ord",
    "output_timing",
    "overflow",
    "phase",
    "pod",
    "rate",
    "raw",
    "req",
    "resume",
    "safe",
    "samples",
    "sim",
    "stack",
    "str",
    "table",
    "target",
    "tick",
    "tick_source",
    "tick_tolerance",
    "ticks",
    "timeout",
    "total",
    "u16",
    "u32",
    "u64",
    "u8",
    "vec",
    "wake",
    "word",
];

/// Ist `word` ein Schluesselwort?
pub fn is_keyword(word: &str) -> bool {
    KEYWORDS.binary_search(&word).is_ok()
}

/// Ist `word` ein kontextuelles Terminal der Grammatik?
pub fn is_contextual(word: &str) -> bool {
    CONTEXTUAL.binary_search(&word).is_ok()
}

/// Ist `word` ein reserviertes Wort?
pub fn is_reserved(word: &str) -> bool {
    RESERVED.binary_search(&word).is_ok()
}
