//! Schluesselwoerter (Referenz 2.2) und reservierte Woerter (2.5), Edition 1.
//!
//! Beide Listen sind sortiert, damit `binary_search` sie durchsucht. Der Test
//! `tests/keywords.rs` liest Abschnitt 2.2 aus `plan/definition.md` und vergleicht;
//! eine Abweichung bricht den Build.

/// Schluesselwoerter: leiten eine Aussage, Deklaration oder Klausel ein oder wirken
/// in Ausdruecken als Operator oder Literal (Regel in 2.2). Die Klauselwoerter des
/// Maschinen- und Zustandsrumpfs (`enter`, `exit`, `loop`, `on`, `when`, `after`)
/// stehen nur dort und sind kontextuell (FB-92).
pub const KEYWORDS: &[&str] = &[
    "abort",
    "alert",
    "always",
    "and",
    "arm",
    "as",
    "assumption",
    "at",
    "block",
    "bound",
    "break",
    "campaign",
    "cancel",
    "case",
    "check",
    "command",
    "const",
    "default",
    "disarm",
    "driver",
    "elif",
    "else",
    "ensures",
    "enum",
    "eventually",
    "every",
    "expect",
    "false",
    "fault",
    "fn",
    "for",
    "has",
    "if",
    "implies",
    "import",
    "in",
    "initial",
    "input",
    "instance",
    "job",
    "log",
    "machine",
    "match",
    "matches",
    "measure",
    "native",
    "never",
    "node",
    "none",
    "not",
    "once",
    "or",
    "output",
    "param",
    "pass",
    "persist",
    "port",
    "profile",
    "program",
    "property",
    "pub",
    "pulse",
    "raise",
    "range",
    "record",
    "repeat",
    "requires",
    "return",
    "scenario",
    "send",
    "sequence",
    "signal",
    "stable",
    "state",
    "step",
    "stop_on",
    "stream",
    "sweep",
    "system",
    "then",
    "trigger",
    "true",
    "tunable",
    "type",
    "unit",
    "unitvec",
    "until",
    "var",
    "verdict",
    "verify",
    "wait",
    "with",
];

/// Reservierte Woerter ohne Bedeutung; als Bezeichner verboten (2.5).
pub const RESERVED: &[&str] = &[
    "async", "await", "catch", "class", "defer", "export", "extern", "global", "impl", "module", "region", "select",
    "spawn", "static", "struct", "throw", "trait", "try", "union", "unsafe", "volatile", "where", "while", "yield",
];

/// Kontextuelle Terminale: alle uebrigen Woerter der Grammatik (2.3). Sie gelten nur an
/// ihrer Stelle und sind sonst Bezeichner; nach einer Zahl werden sie nie als Einheit
/// gelesen (lexer.md L4.3). Der Test vergleicht die Liste mit `grammar/takt.ebnf`.
pub const CONTEXTUAL: &[&str] = &[
    "Duration",
    "Edge",
    "affine",
    "after",
    "align",
    "allowlist",
    "asap",
    "big",
    "bits",
    "bool",
    "boundary",
    "budget",
    "bytes",
    "call",
    "capacity",
    "capacity_bytes",
    "capture",
    "channels",
    "cobs",
    "cost",
    "curated_only",
    "debounce",
    "display",
    "doc",
    "drop",
    "drop_oldest",
    "duration",
    "enter",
    "eq",
    "exit",
    "expect_len",
    "f32",
    "f64",
    "fail",
    "fault_is_fail",
    "fixed",
    "float",
    "follows",
    "framing",
    "from",
    "group",
    "hex",
    "hw",
    "i16",
    "i32",
    "i64",
    "i8",
    "idle",
    "inout",
    "int",
    "integer",
    "irreversible",
    "jitter",
    "label",
    "language",
    "layout",
    "len",
    "length_prefixed",
    "line",
    "lines",
    "little",
    "loop",
    "map",
    "mat",
    "max_age",
    "max_rate",
    "max_slew",
    "mem",
    "min_interval",
    "mmio",
    "monitor",
    "numeric",
    "offset",
    "on",
    "open",
    "ord",
    "output_timing",
    "overflow",
    "overrun",
    "phase",
    "pod",
    "polling",
    "ram",
    "rate",
    "raw",
    "req",
    "resume",
    "safe",
    "samples",
    "sim",
    "stack",
    "str",
    "table",
    "target",
    "tcb_policy",
    "tick",
    "tick_source",
    "tick_tolerance",
    "ticks",
    "timeout",
    "total",
    "u16",
    "u32",
    "u64",
    "u8",
    "unchecked",
    "vec",
    "wake",
    "wcet",
    "when",
    "within",
    "word",
];

/// Reservierte Membernamen der eingebauten Typen (2.5), in der Reihenfolge der
/// Referenz; `wrap_*` steht fuer alle Namen mit diesem Praefix.
pub const RESERVED_MEMBERS: &[&str] = &[
    "valid",
    "suspect",
    "stale",
    "age",
    "reason",
    "or",
    "ok",
    "err",
    "t",
    "seq",
    "text",
    "data",
    "len",
    "count",
    "dropped",
    "malformed",
    "overflowed",
    "free",
    "jitter",
    "time_warped",
    "done",
    "result",
    "state",
    "to",
    "to_float",
    "as",
    "bit",
    "bits",
    "with_bit",
    "wrap_*",
    "min",
    "max",
    "mean",
    "rms",
    "last",
    "transpose",
    "inv",
    "det",
    "solve",
    "cholesky",
    "decode",
    "encode",
    "default",
    "push",
    "append",
    "get",
    "insert",
    "remove",
    "clear",
    "skip",
    "starts_with",
    "contains",
    "armed",
    "fired",
    "pre",
    "post",
    "samples",
    "rate",
    "remaining",
    "truncated",
    "reset",
];

/// Zugriffe der Wrapper (`T?`, `T!E`, Channel, Job- und Trigger-Handle): auf `x.name`
/// ist immer der Wrapper gemeint, darum als Feldnamen verboten (2.5).
pub const WRAPPER_ACCESSORS: &[&str] = &["valid", "suspect", "stale", "age", "reason", "or", "ok", "err"];

/// Namen, die die Bindung eines Musters selbst traegt (8.7): als Capture-Namen verboten.
pub const CAPTURE_NAMES: &[&str] = &["t", "seq", "text", "data"];

/// Vordefinierte offene Enums (2.5) mit den in der Referenz genannten Varianten;
/// `Reason` ist der Wertebereich von `x.reason` (3.5).
pub const OPEN_ENUMS: &[(&str, &[&str])] = &[
    (
        "FaultKind",
        &[
            "CheckFailed",
            "Timeout",
            "Expect",
            "Abort",
            "Runtime",
            "MissingValue",
            "SensorFault",
            "StreamOverflow",
            "JobOverflow",
        ],
    ),
    ("BootReason", &["POWER_ON", "WATCHDOG", "SOFTWARE", "DEEP_SLEEP_WAKE", "TRIAL"]),
    ("ImageState", &["CONFIRMED", "TRIAL"]),
    ("RebootCmd", &["NONE", "RESTART", "DEEP_SLEEP"]),
    ("Quality", &["Good", "Suspect", "Stale", "Bad"]),
    ("JobErr", &[]),
    ("Reason", &[]),
];

/// Ist `word` ein Schluesselwort?
pub fn is_keyword(word: &str) -> bool {
    KEYWORDS.binary_search(&word).is_ok()
}

/// Ist `word` ein kontextuelles Terminal der Grammatik?
pub fn is_contextual(word: &str) -> bool {
    CONTEXTUAL.binary_search(&word).is_ok()
}

/// Ist `word` ein reserviertes Wort?
pub fn is_reserved(word: &str) -> bool {
    RESERVED.binary_search(&word).is_ok()
}
